# Copyright © 2026 Securepoint GmbH. All rights reserved.
#
# This source code includes both proprietary and open-source components.
# Proprietary portions of this code are copyrighted by Securepoint GmbH
# and may not be used, reproduced, or distributed without explicit written permission.
#
# Open-source components are provided under their respective license terms,
# which are detailed in the associated files or within the project directory.
# For access to these license documents, please visit our website or the specific project directory.
#
# Securepoint GmbH assumes no liability for damages or legal infringements resulting from unauthorized use of this code.
# For further information or licensing inquiries, please contact security@securepoint.de or call us at +49 4131 24010.

project_name: unbound-exporter
version: 2

builds:
  - env:
      - CGO_ENABLED=0
    binary: unbound-exporter
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64

dockers_v2:
  - images:
      - "ghcr.io/securepoint/unbound-exporter"
    tags:
      - "v{{ .Version }}"
      - "latest"
    dockerfile: ./Dockerfile
    sbom: false
